### ISSUE TITLE
Not Loaded

### ISSUE THREAD

**Issue by nmluthfi** [wafarifki/WebBucin-V6#1]
Halo mas,

ane coba load lokal project masnya, tapi gak load-load mas. Dia stuck di sini
![image](https://github.com/wafarifki/WebBucin-V6/assets/33769324/32350658-f9ed-4c32-bc9b-7ed907470d6b)

**Comment by wafarifki** [comment]
coba mas bisa dibantu untuk screenshot error log mas di tab console via google chrome developer tools

**Comment by rdculous** [comment]
![Uploading Screenshot (13).png…]()
