### ISSUE TITLE
???

### ISSUE THREAD

**Issue by rdculous** [wafarifki/WebBucin-V6#2]
cara fix ini gimana bang? Access to image at 'file:///D:/web/images/book2/page1.jpg' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome, https, chrome-untrusted.

**Comment by wafarifki** [comment]
> cara fix ini gimana bang? Access to image at 'file:///D:/web/images/book2/page1.jpg' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome, https, chrome-untrusted.

ini kayanya karna file path ke gambar page1.jpg nya ga dapet.. coba mas nya di benerin file pathnya... 

terus coba masnya nonaktifkan terlebih dahulu ekstensi di google chrome nya mas.. karna di saya, saya coba jalankan di local aman mas pake extensi live server di visual studio code..
